# Generated by Django 2.0.5 on 2018-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20180705_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgroup',
            name='grouplist',
            field=models.ForeignKey(on_delete='cascade', related_name='groups', to='todos.GroupList'),
        ),
    ]
