# Generated by Django 2.0.5 on 2018-07-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20180708_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
