# Generated by Django 2.0.5 on 2018-07-09 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_card_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 9, 4, 11, 54, 50616)),
        ),
    ]
